sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install numpy scipy matplotlib h5py xlrd
script:
  - export NGPDIR=../
  - export PYTHONPATH=$PYTHONPATH:$NGPDIR
  - python -m NuGridPy.regression_tests.selftest
notifications:
  slack: nugrid:wTgGR31cFsNUqfytUDZ5ZLug
  email: false
